# $schema: https://golangci-lint.run/jsonschema/golangci.v1.63.jsonschema.json

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

# all available settings of specific linters
linters-settings:
  copyloopvar:
    # Check all assigning the loop variable to another variable.
    # Default: false
    check-alias: true

  cyclop:
    # the maximal code complexity to report
    max-complexity: 20
    # should ignore tests (default false)
    skip-tests: true

  exhaustive:
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true

  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # Default: ["standard", "default"]
    sections:
      - standard    # Captures all standard packages if they do not match another section.
      - default     # Contains all imports that could not be matched to another section type.
      - localmodule # Local module detection is done via reading the module name from the go.mod file in the directory where gci is invoked.

  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20

  goconst:
    # Ignore test files.
    # Default: false
    ignore-tests: true

  gocritic:
    # which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - hugeParam
      - ifElseChain
      - rangeValCopy
      - singleCaseSwitch
      - unnamedResult

    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint` run to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental
      - opinionated

  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 15

  godot:
    # List of regexps for excluding particular comment lines from check.
    # Default: []
    exclude:
      # Exclude todo and fixme comments.
      - "^fixme:"
      - "^todo:"

  goimports:
    local-prefixes: github.com/kenjones-cisco/dapperdox/

  # gomodguard:
  #   blocked:
  #     modules: # List of blocked modules
  #       - github.com/pkg/errors:
  #           recommendations:
  #             - errors
  #             - fmt
  #             - runtime/debug
  #           reason: "Repo has been archived because the functionality for error wrapping is now part of native Golang."

  gosec:
    # Exclude generated files
    # Default: false
    exclude-generated: true

    # Filter out the issues with a lower severity than the given value.
    # Valid options are: low, medium, high.
    # Default: low
    severity: medium

    # Filter out the issues with a lower confidence than the given value.
    # Valid options are: low, medium, high.
    # Default: low
    confidence: medium

  govet:
    enable:
      - fieldalignment
      - shadow

  importas:
    # Do not allow unaliased imports of aliased packages.
    # Default: false
    no-unaliased: true
    # List of aliases
    # Default: []
    alias:
      # third-party aliases
      - pkg: github.com/deckarep/golang-set/v2
        alias: mapset
      - pkg: github.com/orcaman/concurrent-map
        alias: cmap

  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 200
    # tab width in spaces. Default to 1.
    tab-width: 4

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US

  mnd:
    # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    # Allow octal number literals for fs permissions
    ignored-functions:
      - 'os.FileMode'
    # Configuration values are not magic numbers.
    ignored-files:
      - 'config/configurations.go'

  nolintlint:
    # Disable to ensure that all nolint directives actually have an effect. Default is true.
    allow-unused: false
    # Enable to require an explanation of nonzero length after each nolint directive. Default is false.
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed. Default is false.
    require-specific: true

  perfsprint:
    # Optimizes into strings concatenation.
    # Default: true
    #
    # Setting to false. String concatenation is often more confusing and less readable.
    strconcat: false

  stylecheck:
    checks:
      - "all"
      - "-ST1000" # Disable linter for package comments.

  unused:
    # Mark all struct fields that have been written to as used.
    # Default: true
    field-writes-are-uses: false
    # Mark all local variables as used.
    # default: true
    local-variables-are-used: false

linters:
  enable-all: true
  disable:
    - contextcheck
    - depguard
    - err113 # TODO(kenjones): avoid dynamic errors
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen    # TODO(kenjones): refactor code
    - gochecknoglobals
    - gochecknoinits
    - gocognit  # TODO(kenjones): refactor code
    - gocyclo   # TODO(kenjones): refactor code
    - godox
    - gosec   # TODO(kenjones): triggers a panic during scan
    - ireturn
    - musttag
    - nestif
    - nonamedreturns
    - tagliatelle
    - tenv # deprecrated, replaced by usetesting
    - testpackage
    - varnamelen
    - wrapcheck

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

  # Excluding configuration per-path and per-linter
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - ifshort
        - maintidx
        - paralleltest
        - scopelint
        - testpackage

    - path: config/configurations.go|main.go
      text: "forbidden by pattern"
      linters:
        - forbidigo

    - path: discover/apispecs_test.go
      text: "Possible resource leak"
      linters:
        - gocritic

    # TODO(rigdomin): handler this linter at a later time
    - path: formatter/markdown.go|handlers/reference/reference.go
      text: "reassigned, but never used afterwards"
      linters:
        - wastedassign

    # TODO(rigdomin): fix cyclop issue for [load() 27/20] and [resourceFromSchema() 32/20]
    - path: spec/spec.go
      text: "calculated cyclomatic complexity"
      linters:
        - cyclop

    - path: render/render.go
      linters:
        - nlreturn

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
