FROM golang:1.23

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
        zip \
    && rm -rf /var/lib/apt/lists/*

ENV YQ_BIN_VERSION v4.47.1

ENV GOPATH=/go
ENV GOBIN=/go/bin
ENV GOLANGCI_LINT_VERSION "v1.64.8"

RUN wget -O /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_BIN_VERSION}/yq_linux_amd64" \
    && chmod 755 /usr/local/bin/yq

RUN go install golang.org/x/tools/cmd/goimports@v0.24.0 \
    && go install github.com/mitchellh/gox@latest \
    && go install gotest.tools/gotestsum@latest \
    && wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b ${GOBIN} ${GOLANGCI_LINT_VERSION} \
    && rm -rf /go/src/*

ENV CGO_ENABLED=0 \
    GOFLAGS='-buildvcs=false'
